language: python

python: "3.4"

# don't trigger build for tags
branches:
  except: /^v\d/

# build sdist
script: make build

# install twine for uploading to PyPI
before_deploy: pip install twine

deploy:

  # create github release
  - provider: script
    script: make release
    on:
      branch: master

  # deploy to PyPI
  - provider: script

    # upload sdist to PyPI
    script: twine upload -u $PYPI_USERNAME -p $PYPI_PASSWORD dist/*

    # avoid stashing sdist
    skip_cleanup: true

    on:
      branch: master
